import UI.GUI;

public class App {
    public static void main(String[] args) {
        GUI gui = new GUI();

//        App.ElevatorHandler elevatorHandler = new App.ElevatorHandler();
//
//        Random random = new Random();
//        Random rng = new Random();
//
//        // set number for % of return trips generated by generator
//        // i.e. if you set 50, then 50% of requests will be from
//        // floors >0 to first floor
//        int returnTrips = 50;
//
//        for (;;) {
//            if (returnTrips > rng.nextInt(100)) {
//                elevatorHandler.addRequest(new App.Request(random.nextInt(55), 0));
//            } else {
//                elevatorHandler.addRequest(new App.Request(0, random.nextInt(55)));
//            }
//        }

        // to add your own requests, you can add it manually into that for above
    }
}
